#!/bin/bash

if [ "$1" == "" ]
then
echo "USAGE: runl '[.l or .lex FILE']"
else
echo "***LEX***"
echo ""
lex $1 &&
echo ""
echo "***GCC***"
echo ""
gcc lex.yy.c &&
echo ""
echo "***RUN***"
echo ""
./a.out
fi